- name: installing python 
  ansible.builtin.import_role:
    name: common
    tasks_from: python-setup

- name: installing app
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup 

- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app  

- name: deamon reload and starting service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup 