- name: copying mongodb.repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongodb-org-shell
  ansible.builtin.yum:
    name: mongodb-org-shell 
    state: installed

- name: loading schema
  ansible.builtin.shell: mongo --host mongodb.joindevops.cloud < /app/schema/{{component}}.js